#!/bin/bash -l
#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16
echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# loading samtools and tophat modules
# module load tophat #loads 2.1.1 which requires bt2l index files
module load tophat
module load bowtie2
module load boost
module load samtools/0.1.19 
# your commands here
# running tophat
tophat -o ./P0_1_tophat -p 16 -r 200 -G /project/bf528/project_2/reference/annot/mm9.gtf --segment-mismatches=1 --no-novel-juncs  /project/bf528/project_2/reference/mm9  /projectnb/bf528/users/lava_lamp/project_2/P0_1_1.fastq /projectnb/bf528/users/lava_lamp/project_2/P0_1_2.fastq
echo "Job finished: $(date +%F)"
